### ISSUE TITLE
ScrollTo issue

### ISSUE THREAD

**Issue by wutmikee** [sprintly/jquery.pageguide#1]
I have a large DIV that is greater height than most computer monitors (which is okay). My problem is however, I have a guide step on this and when I click the "next Arrow" it highlights this DIV as it should, but it scrolls to the bottom of the DIV - which doesn't make sense. I need to it scroll to the top of each DIV, not the bottom.

Is this possible? I tried modifying the js - but to no luck.

Please help! AMAZING re-work BTW! :)

**Comment by impressiver** [comment]
Yea, this is a known issue - I'll push a fix for it asap.

**Comment by impressiver** [comment]
Let me know if you still see any funky positioning. Thanks!

**Comment by wutmikee** [comment]
Perfect! Thanks! Just update the js file I imagine?

**Comment by impressiver** [comment]
Yep, the fix only touched the `jquery.pageguide.js` file, so updating that should be all you need.

**Comment by wutmikee** [comment]
Thought so. Not a github guy, so wasn't entirely sure. Awesome work! Thanks!
